version: "3.7"

networks:
  dev-media-network:
    driver: bridge

volumes:
  postgresql_data:
    driver: local

services:
  web-server:
    image: nginx
    container_name: dev-media-web-server
    ports:
      - 8000:80
    networks:
      - dev-media-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - database
      - deschamps
      - guanabara
      - akita

  database:
    image: bitnami/postgresql:latest
    container_name: dev-media-database
    ports:
      - '5432:5432'
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    networks:
      - dev-media-network

  deschamps:
    build: .
    container_name: dev-media-deschamps
    environment:
      DEVELOPER_ID: "1"
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
    networks:
      - dev-media-network
    ports:
      - 5001:5005
    depends_on:
      - database

  guanabara:
    build: .
    container_name: dev-media-guanabara
    environment:
      DEVELOPER_ID: "2"
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
    networks:
      - dev-media-network
    ports:
      - 5002:5005
    depends_on:
      - database

  akita:
    build: .
    container_name: dev-media-akita
    environment:
      DEVELOPER_ID: "3"
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
    networks:
      - dev-media-network
    ports:
      - 5003:5005
    depends_on:
      - database
